# Alpenflage Kitty Theme
background            #1D2021
foreground            #C1A376
cursor                #9D2B32
selection_background  #3A4D39
selection_foreground  #C1A376

# Black
color0  #1D2021
color8  #32302F

# Red
color1  #9D2B32
color9  #BA3A42

# Green
color2  #3A4D39
color10 #4F694E

# Yellow
color3  #C1A376
color11 #D5BA8E

# Blue
color4  #456073
color12 #5B7A91

# Magenta
color5  #6B3A47
color13 #854B59

# Cyan
color6  #3F5E5B
color14 #527A76

# White
color7  #A89984
color15 #FBF1C7
